Bean for logged gateway discord client
MitchellTFord/discord-bot pull request #34
Opened 2021-12-29 21:19 UTC by LiangZhang21

closes #20 

-Was able to set up the bean and build the discord bot.
-Was able to have the bot log into discord.

commits collaborated with @nickvichai

2021-12-29 21:50 UTC, MitchellTFord requested changes
A good start, lads (minus the whole leaking of secrets thing)

2021-12-29 21:50 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/GatewayDiscordClientConfig.java
> +  private GatewayDiscordClient client;
```suggestion
```
This class shouldn't need any instance variables. It doesn't look like this was being used anyway

2021-12-29 21:50 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/Application.java
>  public class Application {
All of the changes in `Application.java` are unnecessary and can be reverted

2021-12-29 21:50 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/GatewayDiscordClientConfig.java
> +//    client = DiscordClientBuilder.create("***Token Goes Here***").build().login().block();
The authorization token should come from a properties file or an environment variable (or kind of both, depending on the implementation)

2021-12-29 21:52 UTC, nickvichai commented on src/main/java/com/mitchelltford/discordbot/GatewayDiscordClientConfig.java
> +  private GatewayDiscordClient client;
It's being used in the Bean Method.

2021-12-29 21:54 UTC, nickvichai commented on src/main/java/com/mitchelltford/discordbot/Application.java
>  public class Application {
Sounds good, will remove ApplicationContext, but we need to use the ConfigurableApplicationContext.

2021-12-29 22:02 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/Application.java
>  public class Application {
nah, I meant **all** the changes in the file, not just the one GitHub is previewing

2021-12-29 22:05 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/GatewayDiscordClientConfig.java
> +  private GatewayDiscordClient client;
You don't need to handle the singleton creation and storage, Spring does all of that for you. You just need to write the Bean method

2021-12-29 22:53 UTC, MitchellTFord requested changes

2021-12-29 22:53 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/Application.java
> +import java.io.IOException;
```suggestion
import java.io.IOException;
```
Removed unused import

2021-12-29 22:59 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/GatewayDiscordClientConfig.java
> +  public GatewayDiscordClient gatewayDiscordConfig(@Value("${bot.token}") String token) {
My bad, I mistyped this in the issue
```suggestion
  public GatewayDiscordClient gatewayDiscordClientConfig(@Value("${bot.token}") String token) {
```

2021-12-30 00:04 UTC, MitchellTFord approved these changes

2021-12-30 00:04 UTC, merged