LavaPlayer Basic Functionality
MitchellTFord/discord-bot pull request #42
Opened 2022-01-02 21:30 UTC by LiangZhang21

Added the template & basic functionality for our LavaPlayer

closes #38 

Worked on this issue with @nickvichai

2022-01-02 21:34 UTC, MitchellTFord commented
You should make the PR a draft since it isn't complete. At the moment, it doesn't actually add any funcitonality

2022-01-05 20:16 UTC, LiangZhang21 commented
Added basic functionalities

2022-01-05 20:36 UTC, LiangZhang21 commented
fixed

2022-01-07 07:25 UTC, nickvichai commented
Requesting for review from @MitchellTFord 

Requested changes:

-Imperative to Reactive approach 👍 
-Javadoc comments 👍 
-Added functionalities 👍

2022-01-07 15:14 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/LavaPlayerEventHandler.java
> +  /** check if the queue is ended, if not, we can play the next song. */
```suggestion
  /** check if the queue is ended, if not, we can play the next song. */
  @Override
```
JavaDoc goes on top of annotations

2022-01-08 01:25 UTC, MitchellTFord requested changes
Sorry for not reviewing this yesterday. Good job on what you have so far!

2022-01-08 01:25 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/LavaPlayer.java
> +          }
JavaDoc comments go above the annotations. This is because the annotations are considered part of what's being documented.

2022-01-08 01:25 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/LavaPlayer.java
> +          MessageChannel channel;
I could be misremembering, but didn't we talk about removing this? It doesn't seem like it should be necessary

2022-01-08 01:25 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/LavaPlayer.java
> +  private final LavaPlayerEventHandler eventHandler;
These fields could use comments explaining what they're for. I know this because I don't actually know what they do

2022-01-08 01:25 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/LavaPlayer.java
> + * the Music bot referenced from sedmelluq
If you're going to include the "referenced from sedmelluq" part (which you should), you should link to the documentation you're referencing.

2022-01-08 01:25 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/commands/Stop.java
> +  public Mono<Void> execute(Message message, String args) {
JavaDoc comment should be above the annotation

2022-01-08 01:25 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/commands/Stop.java
> +public class Stop extends DefaultCommand {
JavaDoc comment should be above the annotation

2022-01-08 01:25 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/commands/Skip.java
> +
JavaDoc comment should be above the annotation

2022-01-08 01:25 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/commands/Play.java
> +  public Mono<Void> execute(Message message, String args) {
JavaDoc comment should be above the annotation

2022-01-08 01:25 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/commands/Play.java
> +public class Play extends DefaultCommand {
JavaDoc comment should be above the annotation

2022-01-08 01:25 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/commands/Ping.java
> +
The changes to this class should be reverted

2022-01-08 21:27 UTC, CodeMasterBrandon commented
Nice job!

2022-01-08 21:52 UTC, LiangZhang21 commented on src/main/java/com/mitchelltford/discordbot/LavaPlayer.java
> +          MessageChannel channel;
We can take it a look later, but from what I notice if MessageChannel might not be need, but playerManager is needed to queue up songs

2022-01-08 22:12 UTC, MitchellTFord commented on src/main/java/com/mitchelltford/discordbot/LavaPlayer.java
> +          MessageChannel channel;
@nickvichai This

2022-01-08 22:22 UTC, MitchellTFord approved these changes
👍

2022-01-08 22:23 UTC, merged